[project]
name = 'dividend-splitter'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.revenue-splitter]
path = 'contracts/revenue-splitter.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait-ft]
path = 'contracts/sip-010-trait-ft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
